name: Check Environment Variables

on:
    workflow_dispatch:

jobs:
    check-env-vars:
        runs-on: ubuntu-latest

        steps:
            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Print environment variables
              run: node envCheck